import { Injectable,UnauthorizedException } from '@nestjs/common'; import { JwtService } from '@nestjs/jwt'; import { PrismaService } from '../prisma/prisma.service'; import * as argon2 from 'argon2'; import { createHash,randomBytes,randomUUID } from 'node:crypto';
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const accessSecret=()=>process.env.JWT_ACCESS_SECRET!; const refreshSecret=()=>process.env.JWT_REFRESH_SECRET!;
@Injectable() export class AuthService {
  constructor(private p:PrismaService,private jwt:JwtService){}
  async login(tenantSlug:string,email:string,password:string,meta:{ip?:string;userAgent?:string}) {
    const tenant=await this.p.tenant.findUnique({where:{slug:tenantSlug}}); const user=tenant?await this.p.user.findFirst({where:{email,tenantId:tenant.id}}):null;
    if(!tenant||tenant.status!=='ACTIVE'||!user||user.status!=='ACTIVE'||(user.lockedUntil&&user.lockedUntil>new Date())) throw new UnauthorizedException('Invalid credentials');
    const valid=await argon2.verify(user.passwordHash,password).catch(()=>false);
    if(!valid){const failed=user.failedLoginCount+1;await this.p.user.update({where:{id:user.id},data:{failedLoginCount:failed,lockedUntil:failed>=5?new Date(Date.now()+15*60_000):null}});throw new UnauthorizedException('Invalid credentials');}
    const csrf=randomBytes(32).toString('hex'); const session=await this.p.authSession.create({data:{tenantId:tenant.id,userId:user.id,csrfTokenHash:hash(csrf),ipAddress:meta.ip,userAgent:meta.userAgent,expiresAt:new Date(Date.now()+7*86400_000)}});
    const refresh=await this.issueRefresh(session.id,user.id,tenant.id,randomUUID()); const access=await this.issueAccess(user.id,tenant.id,user.role,user.tokenVersion,session.id);
    await this.p.user.update({where:{id:user.id},data:{failedLoginCount:0,lockedUntil:null,lastLoginAt:new Date()}}); await this.audit(tenant.id,user.id,'auth.login','User',user.id);
    return {access,refresh,csrf,user:{id:user.id,email:user.email,role:user.role},tenant:{id:tenant.id,slug:tenant.slug,name:tenant.name},sessionId:session.id};
  }
  private issueAccess(userId:string,tenantId:string,role:string,ver:number,sid:string){return this.jwt.signAsync({sub:userId,tenantId,role,ver,sid,type:'access'},{secret:accessSecret(),expiresIn:'15m'});}
  private async issueRefresh(sessionId:string,userId:string,tenantId:string,familyId:string){const raw=randomBytes(48).toString('base64url');await this.p.refreshToken.create({data:{tenantId,userId,sessionId,familyId,tokenHash:hash(raw),expiresAt:new Date(Date.now()+7*86400_000)}});return raw;}
  async refresh(raw:string){const record=await this.p.refreshToken.findUnique({where:{tokenHash:hash(raw)},include:{session:true,user:true,tenant:true}});if(!record||record.expiresAt<=new Date()||record.revokedAt||record.session.revokedAt||record.session.expiresAt<=new Date())throw new UnauthorizedException('Invalid refresh session');if(record.usedAt){await this.p.refreshToken.updateMany({where:{familyId:record.familyId},data:{revokedAt:new Date()}});await this.p.authSession.update({where:{id:record.sessionId},data:{revokedAt:new Date()}});throw new UnauthorizedException('Refresh token reuse detected');}await this.p.refreshToken.update({where:{id:record.id},data:{usedAt:new Date()}});const next=await this.issueRefresh(record.sessionId,record.userId,record.tenantId,record.familyId);const access=await this.issueAccess(record.userId,record.tenantId,record.user.role,record.user.tokenVersion,record.sessionId);return {access,refresh:next};}
  async logout(sessionId:string,all:boolean){const session=await this.p.authSession.findUnique({where:{id:sessionId}});if(!session)return;if(all){await this.p.user.update({where:{id:session.userId},data:{tokenVersion:{increment:1}}});await this.p.authSession.updateMany({where:{userId:session.userId,tenantId:session.tenantId,revokedAt:null},data:{revokedAt:new Date()}});await this.p.refreshToken.updateMany({where:{userId:session.userId,tenantId:session.tenantId,revokedAt:null},data:{revokedAt:new Date()}});}else{await this.p.authSession.update({where:{id:sessionId},data:{revokedAt:new Date()}});await this.p.refreshToken.updateMany({where:{sessionId,revokedAt:null},data:{revokedAt:new Date()}});}}
  async forgotPassword(tenantSlug:string,email:string){const tenant=await this.p.tenant.findUnique({where:{slug:tenantSlug}});const user=tenant?await this.p.user.findFirst({where:{tenantId:tenant.id,email}}):null;if(!user)return {ok:true};const raw=randomBytes(32).toString('base64url');await this.p.passwordResetToken.create({data:{tenantId:user.tenantId!,userId:user.id,tokenHash:hash(raw),expiresAt:new Date(Date.now()+30*60_000)}});return process.env.NODE_ENV==='development'?{ok:true,token:raw}:{ok:true};}
  async resetPassword(raw:string,password:string){const token=await this.p.passwordResetToken.findUnique({where:{tokenHash:hash(raw)}});if(!token||token.usedAt||token.expiresAt<=new Date())throw new UnauthorizedException('Invalid reset token');const passwordHash=await argon2.hash(password);await this.p.$transaction([this.p.user.update({where:{id:token.userId},data:{passwordHash,tokenVersion:{increment:1},failedLoginCount:0,lockedUntil:null}}),this.p.passwordResetToken.update({where:{id:token.id},data:{usedAt:new Date()}}),this.p.authSession.updateMany({where:{userId:token.userId,revokedAt:null},data:{revokedAt:new Date()}}),this.p.refreshToken.updateMany({where:{userId:token.userId,revokedAt:null},data:{revokedAt:new Date()}})]);return {ok:true};}
  private audit(tenantId:string,userId:string,action:string,entity:string,entityId:string){return this.p.auditEvent.create({data:{tenantId,userId,action,entity,entityId,correlationId:randomUUID()}})}
}
